openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
  description: E-commerce ilovasi uchun API endpointlari

servers:
  - url: http://localhost:3000/api

paths:
  /products:
    get:
      summary: Barcha mahsulotlarni olish
      responses:
        '200':
          description: Muvaffaqiyatli so'rov
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Yangi mahsulot qo'shish
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Mahsulot muvaffaqiyatli qo'shildi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '401':
          description: Autentifikatsiya xatosi

  /products/{id}:
    put:
      summary: Mavjud mahsulotni yangilash
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Mahsulot muvaffaqiyatli yangilandi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '401':
          description: Autentifikatsiya xatosi
    delete:
      summary: Mahsulotni o'chirish
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Mahsulot muvaffaqiyatli o'chirildi
        '401':
          description: Autentifikatsiya xatosi

  /users:
    get:
      summary: Barcha foydalanuvchilarni olish
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Muvaffaqiyatli so'rov
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          description: Autentifikatsiya xatosi
        '403':
          description: Ruxsat berilmagan

  /user:
    post:
      summary: Yangi foydalanuvchi qo'shish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: Foydalanuvchi muvaffaqiyatli qo'shildi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Noto'g'ri so'rov

  /login:
    post:
      summary: Foydalanuvchini tizimga kiritish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        '200':
          description: Muvaffaqiyatli kirish
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Noto'g'ri ma'lumotlar

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        price:
          type: number
        description:
          type: string
        imageUrl:
          type: string
    ProductInput:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
        description:
          type: string
        imageUrl:
          type: string
    User:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        email:
          type: string
        role:
          type: string
    UserInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
    LoginInput:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT